version: "3.8"

services:
  express_app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: "8080"
      DATABASE_URL: "postgresql://backend_lab3_db_user:mLYob0dKC6S9gfeWbUIygtq0qTgUsom1@dpg-d44h5immcj7s739u605g-a.oregon-postgres.render.com/backend_lab3_db"
    ports:
      - "8080:8080"
